Repository ComicScrip/lyon-react-mars22-p2g3, pull requests merged in 2022-05, with the labels that each got.

#36 Details
  package-lock.json
  public/assets/logo_cinechill.png
  public/index.html
  public/manifest.json
  src/Css/Details.css
  src/Css/Navbar.css
  src/Css/Suggest.css
  src/components/DisplayMovie.js
  src/components/DisplayQuote.js
  src/components/Header.js
  src/components/SocialMedia.js
  src/routes/Details.js
Labels: READY FOR VALIDATION

#46 changes on questionary after review
  src/routes/Questionary.js
Labels: READY FOR VALIDATION

#43 Resultpage
  .github/ISSUE_TEMPLATE/user-story.md
  package.json
  src/Css/Result.css
  src/components/Card.js
  src/routes/Result.js
Labels: READY FOR VALIDATION, CONFLICTS

#50 Moviepage gig
  public/assets/pulp.gif
  public/img/pulp.gif
  src/Css/MovieGif.css
  src/Css/Suggest.css
  src/components/Header.js
  src/components/MovieGif.js
  src/components/MovieGifs.js
  src/img/movie.png
  src/img/pulp.gif
  src/routes/MovieGif.js
  src/routes/Suggest.js
Labels: READY FOR VALIDATION

#48 question 4 done
  package-lock.json
  package.json
  src/routes/Questionary.js
Labels: READY FOR VALIDATION

#51 Selector
  src/Css/Home.css
  src/Css/Result.css
  src/components/Caroussel.js
  src/img/load.gif
  src/routes/Details.js
  src/routes/Home.js
  src/routes/Questionary.js
  src/routes/Result.js
Labels: READY FOR PROD
